#!/bin/sh

case "$1" in
  start)
    { { /retroarch/start.sh && halt; } || echo "TODO: handle error"; } &
    ;;
  stop)
    killall -9 retroarch
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
